// AUTH constants
export const USER_KEY = 'USER_KEY',
    AUTH_REQUEST = 'AUTH_REQUEST',
    AUTHORIZED = 'AUTHORIZED';

//LAYOUT constants
export const BTN_SPINNER_ON = 'BTN_SPINNER_ON',
    BTN_SPINNER_OFF = 'BTN_SPINNER_OFF',
    LOADER_ON = 'LOADER_ON',
    LOADER_OFF = 'LOADER_OFF';

// Home
export const LOAD_HOME = 'LOAD_HOME',
    RECEIVE_HOME_DATA = 'RECEIVE_HOME_DATA',
    ERROR_RECEIVING_HOME_DATA = 'ERROR_RECEIVING_HOME_DATA',
    RECEIVE_MORE_HOME_DATA = 'RECEIVE_MORE_HOME_DATA';


    //Navigation
    export const NAVIGATE = 'NAVIGATE';